version: '3.8'

# Jenkins and SonarQube CI/CD Infrastructure
services:
  

  sonarqube:
    image: sonarqube:8.9-community
    container_name: sonarqube-credittransfer
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar_password_2024
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_conf:/opt/sonarqube/conf
   
      
    depends_on:
      - postgres-sonar
    restart: unless-stopped
    networks:
      - ci-cd-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  postgres-sonar:
    image: postgres:15.4
    container_name: postgres-sonar-credittransfer
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar_password_2024
      - POSTGRES_DB=sonar
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - postgres_sonar_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ci-cd-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar -d sonar"]
      interval: 30s
      timeout: 10s
      retries: 5

  nexus:
    image: sonatype/nexus3:3.44.0
    container_name: nexus-credittransfer
    ports:
      - "8081:8081"
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - INSTALL4J_ADD_VM_PARAMS=-Xms1024m -Xmx2048m -XX:MaxDirectMemorySize=3072m
    volumes:
      - nexus_data:/nexus-data
      - ./nexus/nexus.properties:/opt/sonatype/nexus/etc/nexus.properties
    restart: unless-stopped
    networks:
      - ci-cd-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/service/rest/v1/status || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s

  # Add Prometheus for Jenkins monitoring





volumes:
  jenkins_home:
  sonarqube_data:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_conf:
    driver: local
  postgres_sonar_data:
    driver: local
  nexus_data:
    driver: local
  prometheus_jenkins_data:
    driver: local
  grafana_jenkins_data:
    driver: local

networks:
  ci-cd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16 