//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CreditTransferModel", "FK_ErrorLog_ErrorLog", "Log", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CreditTransferEngine.DataAccess.Log), "ErrorLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CreditTransferEngine.DataAccess.ErrorLog), true)]
[assembly: EdmRelationshipAttribute("CreditTransferModel", "FK_Transaction_TransactionStatus", "TransactionStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CreditTransferEngine.DataAccess.TransactionStatu), "Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CreditTransferEngine.DataAccess.Transaction), true)]

#endregion

namespace CreditTransferEngine.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CreditTransferEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CreditTransferEntities object using the connection string found in the 'CreditTransferEntities' section of the application configuration file.
        /// </summary>
        public CreditTransferEntities() : base("name=CreditTransferEntities", "CreditTransferEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CreditTransferEntities object.
        /// </summary>
        public CreditTransferEntities(string connectionString) : base(connectionString, "CreditTransferEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CreditTransferEntities object.
        /// </summary>
        public CreditTransferEntities(EntityConnection connection) : base(connection, "CreditTransferEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ErrorLog> ErrorLogs
        {
            get
            {
                if ((_ErrorLogs == null))
                {
                    _ErrorLogs = base.CreateObjectSet<ErrorLog>("ErrorLogs");
                }
                return _ErrorLogs;
            }
        }
        private ObjectSet<ErrorLog> _ErrorLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log> Logs
        {
            get
            {
                if ((_Logs == null))
                {
                    _Logs = base.CreateObjectSet<Log>("Logs");
                }
                return _Logs;
            }
        }
        private ObjectSet<Log> _Logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaction> Transactions
        {
            get
            {
                if ((_Transactions == null))
                {
                    _Transactions = base.CreateObjectSet<Transaction>("Transactions");
                }
                return _Transactions;
            }
        }
        private ObjectSet<Transaction> _Transactions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TransactionStatu> TransactionStatus
        {
            get
            {
                if ((_TransactionStatus == null))
                {
                    _TransactionStatus = base.CreateObjectSet<TransactionStatu>("TransactionStatus");
                }
                return _TransactionStatus;
            }
        }
        private ObjectSet<TransactionStatu> _TransactionStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TransferConfig> TransferConfigs
        {
            get
            {
                if ((_TransferConfigs == null))
                {
                    _TransferConfigs = base.CreateObjectSet<TransferConfig>("TransferConfigs");
                }
                return _TransferConfigs;
            }
        }
        private ObjectSet<TransferConfig> _TransferConfigs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Message>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Message> _Messages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ErrorLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToErrorLogs(ErrorLog errorLog)
        {
            base.AddObject("ErrorLogs", errorLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogs(Log log)
        {
            base.AddObject("Logs", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactions(Transaction transaction)
        {
            base.AddObject("Transactions", transaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TransactionStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactionStatus(TransactionStatu transactionStatu)
        {
            base.AddObject("TransactionStatus", transactionStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TransferConfigs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransferConfigs(TransferConfig transferConfig)
        {
            base.AddObject("TransferConfigs", transferConfig);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CreditTransferModel", Name="ErrorLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ErrorLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ErrorLog object.
        /// </summary>
        /// <param name="errorLogId">Initial value of the ErrorLogId property.</param>
        /// <param name="exception">Initial value of the Exception property.</param>
        /// <param name="stackTrace">Initial value of the StackTrace property.</param>
        /// <param name="logId">Initial value of the LogId property.</param>
        public static ErrorLog CreateErrorLog(global::System.Int32 errorLogId, global::System.String exception, global::System.String stackTrace, global::System.Int32 logId)
        {
            ErrorLog errorLog = new ErrorLog();
            errorLog.ErrorLogId = errorLogId;
            errorLog.Exception = exception;
            errorLog.StackTrace = stackTrace;
            errorLog.LogId = logId;
            return errorLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ErrorLogId
        {
            get
            {
                return _ErrorLogId;
            }
            set
            {
                if (_ErrorLogId != value)
                {
                    OnErrorLogIdChanging(value);
                    ReportPropertyChanging("ErrorLogId");
                    _ErrorLogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ErrorLogId");
                    OnErrorLogIdChanged();
                }
            }
        }
        private global::System.Int32 _ErrorLogId;
        partial void OnErrorLogIdChanging(global::System.Int32 value);
        partial void OnErrorLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Exception
        {
            get
            {
                return _Exception;
            }
            set
            {
                OnExceptionChanging(value);
                ReportPropertyChanging("Exception");
                _Exception = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Exception");
                OnExceptionChanged();
            }
        }
        private global::System.String _Exception;
        partial void OnExceptionChanging(global::System.String value);
        partial void OnExceptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StackTrace
        {
            get
            {
                return _StackTrace;
            }
            set
            {
                OnStackTraceChanging(value);
                ReportPropertyChanging("StackTrace");
                _StackTrace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StackTrace");
                OnStackTraceChanged();
            }
        }
        private global::System.String _StackTrace;
        partial void OnStackTraceChanging(global::System.String value);
        partial void OnStackTraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogId
        {
            get
            {
                return _LogId;
            }
            set
            {
                OnLogIdChanging(value);
                ReportPropertyChanging("LogId");
                _LogId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogId");
                OnLogIdChanged();
            }
        }
        private global::System.Int32 _LogId;
        partial void OnLogIdChanging(global::System.Int32 value);
        partial void OnLogIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CreditTransferModel", "FK_ErrorLog_ErrorLog", "Log")]
        public Log Log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Log>("CreditTransferModel.FK_ErrorLog_ErrorLog", "Log").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Log>("CreditTransferModel.FK_ErrorLog_ErrorLog", "Log").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Log> LogReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Log>("CreditTransferModel.FK_ErrorLog_ErrorLog", "Log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Log>("CreditTransferModel.FK_ErrorLog_ErrorLog", "Log", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CreditTransferModel", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log object.
        /// </summary>
        /// <param name="logId">Initial value of the LogId property.</param>
        /// <param name="receivedRequest">Initial value of the ReceivedRequest property.</param>
        /// <param name="requestedBy">Initial value of the RequestedBy property.</param>
        /// <param name="requestDate">Initial value of the RequestDate property.</param>
        public static Log CreateLog(global::System.Int32 logId, global::System.String receivedRequest, global::System.String requestedBy, global::System.DateTime requestDate)
        {
            Log log = new Log();
            log.LogId = logId;
            log.ReceivedRequest = receivedRequest;
            log.RequestedBy = requestedBy;
            log.RequestDate = requestDate;
            return log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogId
        {
            get
            {
                return _LogId;
            }
            set
            {
                if (_LogId != value)
                {
                    OnLogIdChanging(value);
                    ReportPropertyChanging("LogId");
                    _LogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogId");
                    OnLogIdChanged();
                }
            }
        }
        private global::System.Int32 _LogId;
        partial void OnLogIdChanging(global::System.Int32 value);
        partial void OnLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReceivedRequest
        {
            get
            {
                return _ReceivedRequest;
            }
            set
            {
                OnReceivedRequestChanging(value);
                ReportPropertyChanging("ReceivedRequest");
                _ReceivedRequest = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReceivedRequest");
                OnReceivedRequestChanged();
            }
        }
        private global::System.String _ReceivedRequest;
        partial void OnReceivedRequestChanging(global::System.String value);
        partial void OnReceivedRequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MethodName
        {
            get
            {
                return _MethodName;
            }
            set
            {
                OnMethodNameChanging(value);
                ReportPropertyChanging("MethodName");
                _MethodName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MethodName");
                OnMethodNameChanged();
            }
        }
        private global::System.String _MethodName;
        partial void OnMethodNameChanging(global::System.String value);
        partial void OnMethodNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestedBy
        {
            get
            {
                return _RequestedBy;
            }
            set
            {
                OnRequestedByChanging(value);
                ReportPropertyChanging("RequestedBy");
                _RequestedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestedBy");
                OnRequestedByChanged();
            }
        }
        private global::System.String _RequestedBy;
        partial void OnRequestedByChanging(global::System.String value);
        partial void OnRequestedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusText
        {
            get
            {
                return _StatusText;
            }
            set
            {
                OnStatusTextChanging(value);
                ReportPropertyChanging("StatusText");
                _StatusText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusText");
                OnStatusTextChanged();
            }
        }
        private global::System.String _StatusText;
        partial void OnStatusTextChanging(global::System.String value);
        partial void OnStatusTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private global::System.DateTime _RequestDate;
        partial void OnRequestDateChanging(global::System.DateTime value);
        partial void OnRequestDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CreditTransferModel", "FK_ErrorLog_ErrorLog", "ErrorLog")]
        public EntityCollection<ErrorLog> ErrorLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ErrorLog>("CreditTransferModel.FK_ErrorLog_ErrorLog", "ErrorLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ErrorLog>("CreditTransferModel.FK_ErrorLog_ErrorLog", "ErrorLog", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CreditTransferModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="textEn">Initial value of the TextEn property.</param>
        /// <param name="textAr">Initial value of the TextAr property.</param>
        public static Message CreateMessage(global::System.Int32 id, global::System.String key, global::System.String textEn, global::System.String textAr)
        {
            Message message = new Message();
            message.Id = id;
            message.Key = key;
            message.TextEn = textEn;
            message.TextAr = textAr;
            return message;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TextEn
        {
            get
            {
                return _TextEn;
            }
            set
            {
                OnTextEnChanging(value);
                ReportPropertyChanging("TextEn");
                _TextEn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TextEn");
                OnTextEnChanged();
            }
        }
        private global::System.String _TextEn;
        partial void OnTextEnChanging(global::System.String value);
        partial void OnTextEnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TextAr
        {
            get
            {
                return _TextAr;
            }
            set
            {
                OnTextArChanging(value);
                ReportPropertyChanging("TextAr");
                _TextAr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TextAr");
                OnTextArChanged();
            }
        }
        private global::System.String _TextAr;
        partial void OnTextArChanging(global::System.String value);
        partial void OnTextArChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CreditTransferModel", Name="Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaction object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sourceMsisdn">Initial value of the SourceMsisdn property.</param>
        /// <param name="destinationMsisdn">Initial value of the DestinationMsisdn property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="pIN">Initial value of the PIN property.</param>
        /// <param name="isFromCustomer">Initial value of the IsFromCustomer property.</param>
        /// <param name="isEventReserved">Initial value of the IsEventReserved property.</param>
        /// <param name="isAmountTransfered">Initial value of the IsAmountTransfered property.</param>
        /// <param name="isEventCharged">Initial value of the IsEventCharged property.</param>
        /// <param name="isEventCancelled">Initial value of the IsEventCancelled property.</param>
        /// <param name="isExpiryExtended">Initial value of the IsExpiryExtended property.</param>
        /// <param name="extensionDays">Initial value of the ExtensionDays property.</param>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        /// <param name="numberOfRetries">Initial value of the NumberOfRetries property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        public static Transaction CreateTransaction(global::System.Int64 id, global::System.String sourceMsisdn, global::System.String destinationMsisdn, global::System.Decimal amount, global::System.String pIN, global::System.Boolean isFromCustomer, global::System.Boolean isEventReserved, global::System.Boolean isAmountTransfered, global::System.Boolean isEventCharged, global::System.Boolean isEventCancelled, global::System.Boolean isExpiryExtended, global::System.Int32 extensionDays, global::System.Int32 reservationId, global::System.Byte statusId, global::System.Int32 numberOfRetries, global::System.DateTime creationDate, global::System.String createdBy)
        {
            Transaction transaction = new Transaction();
            transaction.Id = id;
            transaction.SourceMsisdn = sourceMsisdn;
            transaction.DestinationMsisdn = destinationMsisdn;
            transaction.Amount = amount;
            transaction.PIN = pIN;
            transaction.IsFromCustomer = isFromCustomer;
            transaction.IsEventReserved = isEventReserved;
            transaction.IsAmountTransfered = isAmountTransfered;
            transaction.IsEventCharged = isEventCharged;
            transaction.IsEventCancelled = isEventCancelled;
            transaction.IsExpiryExtended = isExpiryExtended;
            transaction.ExtensionDays = extensionDays;
            transaction.ReservationId = reservationId;
            transaction.StatusId = statusId;
            transaction.NumberOfRetries = numberOfRetries;
            transaction.CreationDate = creationDate;
            transaction.CreatedBy = createdBy;
            return transaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SourceMsisdn
        {
            get
            {
                return _SourceMsisdn;
            }
            set
            {
                OnSourceMsisdnChanging(value);
                ReportPropertyChanging("SourceMsisdn");
                _SourceMsisdn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SourceMsisdn");
                OnSourceMsisdnChanged();
            }
        }
        private global::System.String _SourceMsisdn;
        partial void OnSourceMsisdnChanging(global::System.String value);
        partial void OnSourceMsisdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DestinationMsisdn
        {
            get
            {
                return _DestinationMsisdn;
            }
            set
            {
                OnDestinationMsisdnChanging(value);
                ReportPropertyChanging("DestinationMsisdn");
                _DestinationMsisdn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DestinationMsisdn");
                OnDestinationMsisdnChanged();
            }
        }
        private global::System.String _DestinationMsisdn;
        partial void OnDestinationMsisdnChanging(global::System.String value);
        partial void OnDestinationMsisdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFromCustomer
        {
            get
            {
                return _IsFromCustomer;
            }
            set
            {
                OnIsFromCustomerChanging(value);
                ReportPropertyChanging("IsFromCustomer");
                _IsFromCustomer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFromCustomer");
                OnIsFromCustomerChanged();
            }
        }
        private global::System.Boolean _IsFromCustomer;
        partial void OnIsFromCustomerChanging(global::System.Boolean value);
        partial void OnIsFromCustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEventReserved
        {
            get
            {
                return _IsEventReserved;
            }
            set
            {
                OnIsEventReservedChanging(value);
                ReportPropertyChanging("IsEventReserved");
                _IsEventReserved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEventReserved");
                OnIsEventReservedChanged();
            }
        }
        private global::System.Boolean _IsEventReserved;
        partial void OnIsEventReservedChanging(global::System.Boolean value);
        partial void OnIsEventReservedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAmountTransfered
        {
            get
            {
                return _IsAmountTransfered;
            }
            set
            {
                OnIsAmountTransferedChanging(value);
                ReportPropertyChanging("IsAmountTransfered");
                _IsAmountTransfered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAmountTransfered");
                OnIsAmountTransferedChanged();
            }
        }
        private global::System.Boolean _IsAmountTransfered;
        partial void OnIsAmountTransferedChanging(global::System.Boolean value);
        partial void OnIsAmountTransferedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEventCharged
        {
            get
            {
                return _IsEventCharged;
            }
            set
            {
                OnIsEventChargedChanging(value);
                ReportPropertyChanging("IsEventCharged");
                _IsEventCharged = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEventCharged");
                OnIsEventChargedChanged();
            }
        }
        private global::System.Boolean _IsEventCharged;
        partial void OnIsEventChargedChanging(global::System.Boolean value);
        partial void OnIsEventChargedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEventCancelled
        {
            get
            {
                return _IsEventCancelled;
            }
            set
            {
                OnIsEventCancelledChanging(value);
                ReportPropertyChanging("IsEventCancelled");
                _IsEventCancelled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEventCancelled");
                OnIsEventCancelledChanged();
            }
        }
        private global::System.Boolean _IsEventCancelled;
        partial void OnIsEventCancelledChanging(global::System.Boolean value);
        partial void OnIsEventCancelledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsExpiryExtended
        {
            get
            {
                return _IsExpiryExtended;
            }
            set
            {
                OnIsExpiryExtendedChanging(value);
                ReportPropertyChanging("IsExpiryExtended");
                _IsExpiryExtended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpiryExtended");
                OnIsExpiryExtendedChanged();
            }
        }
        private global::System.Boolean _IsExpiryExtended;
        partial void OnIsExpiryExtendedChanging(global::System.Boolean value);
        partial void OnIsExpiryExtendedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExtensionDays
        {
            get
            {
                return _ExtensionDays;
            }
            set
            {
                OnExtensionDaysChanging(value);
                ReportPropertyChanging("ExtensionDays");
                _ExtensionDays = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExtensionDays");
                OnExtensionDaysChanged();
            }
        }
        private global::System.Int32 _ExtensionDays;
        partial void OnExtensionDaysChanging(global::System.Int32 value);
        partial void OnExtensionDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                OnReservationIdChanging(value);
                ReportPropertyChanging("ReservationId");
                _ReservationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReservationId");
                OnReservationIdChanged();
            }
        }
        private global::System.Int32 _ReservationId;
        partial void OnReservationIdChanging(global::System.Int32 value);
        partial void OnReservationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private global::System.Byte _StatusId;
        partial void OnStatusIdChanging(global::System.Byte value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfRetries
        {
            get
            {
                return _NumberOfRetries;
            }
            set
            {
                OnNumberOfRetriesChanging(value);
                ReportPropertyChanging("NumberOfRetries");
                _NumberOfRetries = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfRetries");
                OnNumberOfRetriesChanged();
            }
        }
        private global::System.Int32 _NumberOfRetries;
        partial void OnNumberOfRetriesChanging(global::System.Int32 value);
        partial void OnNumberOfRetriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModificationDate
        {
            get
            {
                return _ModificationDate;
            }
            set
            {
                OnModificationDateChanging(value);
                ReportPropertyChanging("ModificationDate");
                _ModificationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModificationDate");
                OnModificationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModificationDate;
        partial void OnModificationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModificationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CreditTransferModel", "FK_Transaction_TransactionStatus", "TransactionStatus")]
        public TransactionStatu TransactionStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TransactionStatu>("CreditTransferModel.FK_Transaction_TransactionStatus", "TransactionStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TransactionStatu>("CreditTransferModel.FK_Transaction_TransactionStatus", "TransactionStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TransactionStatu> TransactionStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TransactionStatu>("CreditTransferModel.FK_Transaction_TransactionStatus", "TransactionStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TransactionStatu>("CreditTransferModel.FK_Transaction_TransactionStatus", "TransactionStatus", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CreditTransferModel", Name="TransactionStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TransactionStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TransactionStatu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="statusText">Initial value of the StatusText property.</param>
        public static TransactionStatu CreateTransactionStatu(global::System.Byte id, global::System.String statusText)
        {
            TransactionStatu transactionStatu = new TransactionStatu();
            transactionStatu.Id = id;
            transactionStatu.StatusText = statusText;
            return transactionStatu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Byte _Id;
        partial void OnIdChanging(global::System.Byte value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatusText
        {
            get
            {
                return _StatusText;
            }
            set
            {
                OnStatusTextChanging(value);
                ReportPropertyChanging("StatusText");
                _StatusText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StatusText");
                OnStatusTextChanged();
            }
        }
        private global::System.String _StatusText;
        partial void OnStatusTextChanging(global::System.String value);
        partial void OnStatusTextChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CreditTransferModel", "FK_Transaction_TransactionStatus", "Transaction")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("CreditTransferModel.FK_Transaction_TransactionStatus", "Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("CreditTransferModel.FK_Transaction_TransactionStatus", "Transaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CreditTransferModel", Name="TransferConfig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TransferConfig : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TransferConfig object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nobillSubscritpionType">Initial value of the NobillSubscritpionType property.</param>
        /// <param name="creditTransferCustomerService">Initial value of the CreditTransferCustomerService property.</param>
        public static TransferConfig CreateTransferConfig(global::System.Int32 id, global::System.String nobillSubscritpionType, global::System.String creditTransferCustomerService)
        {
            TransferConfig transferConfig = new TransferConfig();
            transferConfig.ID = id;
            transferConfig.NobillSubscritpionType = nobillSubscritpionType;
            transferConfig.CreditTransferCustomerService = creditTransferCustomerService;
            return transferConfig;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NobillSubscritpionType
        {
            get
            {
                return _NobillSubscritpionType;
            }
            set
            {
                OnNobillSubscritpionTypeChanging(value);
                ReportPropertyChanging("NobillSubscritpionType");
                _NobillSubscritpionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NobillSubscritpionType");
                OnNobillSubscritpionTypeChanged();
            }
        }
        private global::System.String _NobillSubscritpionType;
        partial void OnNobillSubscritpionTypeChanging(global::System.String value);
        partial void OnNobillSubscritpionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransferCounterName
        {
            get
            {
                return _TransferCounterName;
            }
            set
            {
                OnTransferCounterNameChanging(value);
                ReportPropertyChanging("TransferCounterName");
                _TransferCounterName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransferCounterName");
                OnTransferCounterNameChanged();
            }
        }
        private global::System.String _TransferCounterName;
        partial void OnTransferCounterNameChanging(global::System.String value);
        partial void OnTransferCounterNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreditTransferCustomerService
        {
            get
            {
                return _CreditTransferCustomerService;
            }
            set
            {
                OnCreditTransferCustomerServiceChanging(value);
                ReportPropertyChanging("CreditTransferCustomerService");
                _CreditTransferCustomerService = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreditTransferCustomerService");
                OnCreditTransferCustomerServiceChanged();
            }
        }
        private global::System.String _CreditTransferCustomerService;
        partial void OnCreditTransferCustomerServiceChanging(global::System.String value);
        partial void OnCreditTransferCustomerServiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DailyTransferCountLimit
        {
            get
            {
                return _DailyTransferCountLimit;
            }
            set
            {
                OnDailyTransferCountLimitChanging(value);
                ReportPropertyChanging("DailyTransferCountLimit");
                _DailyTransferCountLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DailyTransferCountLimit");
                OnDailyTransferCountLimitChanged();
            }
        }
        private Nullable<global::System.Int32> _DailyTransferCountLimit;
        partial void OnDailyTransferCountLimitChanging(Nullable<global::System.Int32> value);
        partial void OnDailyTransferCountLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MinTransferAmount
        {
            get
            {
                return _MinTransferAmount;
            }
            set
            {
                OnMinTransferAmountChanging(value);
                ReportPropertyChanging("MinTransferAmount");
                _MinTransferAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinTransferAmount");
                OnMinTransferAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _MinTransferAmount;
        partial void OnMinTransferAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnMinTransferAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TransferFeesEventId
        {
            get
            {
                return _TransferFeesEventId;
            }
            set
            {
                OnTransferFeesEventIdChanging(value);
                ReportPropertyChanging("TransferFeesEventId");
                _TransferFeesEventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransferFeesEventId");
                OnTransferFeesEventIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TransferFeesEventId;
        partial void OnTransferFeesEventIdChanging(Nullable<global::System.Int32> value);
        partial void OnTransferFeesEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MinPostTransferBalance
        {
            get
            {
                return _MinPostTransferBalance;
            }
            set
            {
                OnMinPostTransferBalanceChanging(value);
                ReportPropertyChanging("MinPostTransferBalance");
                _MinPostTransferBalance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinPostTransferBalance");
                OnMinPostTransferBalanceChanged();
            }
        }
        private Nullable<global::System.Decimal> _MinPostTransferBalance;
        partial void OnMinPostTransferBalanceChanging(Nullable<global::System.Decimal> value);
        partial void OnMinPostTransferBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MaxTransferAmount
        {
            get
            {
                return _MaxTransferAmount;
            }
            set
            {
                OnMaxTransferAmountChanging(value);
                ReportPropertyChanging("MaxTransferAmount");
                _MaxTransferAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxTransferAmount");
                OnMaxTransferAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _MaxTransferAmount;
        partial void OnMaxTransferAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnMaxTransferAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubscriptionType
        {
            get
            {
                return _SubscriptionType;
            }
            set
            {
                OnSubscriptionTypeChanging(value);
                ReportPropertyChanging("SubscriptionType");
                _SubscriptionType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubscriptionType");
                OnSubscriptionTypeChanged();
            }
        }
        private global::System.String _SubscriptionType;
        partial void OnSubscriptionTypeChanging(global::System.String value);
        partial void OnSubscriptionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TransferToOtherOperator
        {
            get
            {
                return _TransferToOtherOperator;
            }
            set
            {
                OnTransferToOtherOperatorChanging(value);
                ReportPropertyChanging("TransferToOtherOperator");
                _TransferToOtherOperator = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransferToOtherOperator");
                OnTransferToOtherOperatorChanged();
            }
        }
        private Nullable<global::System.Boolean> _TransferToOtherOperator;
        partial void OnTransferToOtherOperatorChanging(Nullable<global::System.Boolean> value);
        partial void OnTransferToOtherOperatorChanged();

        #endregion

    
    }

    #endregion

    
}
