//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTransferTestClient.CreditTransfer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditTransfer.ICreditTransferService")]
    public interface ICreditTransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditTransferService/TransferCredit", ReplyAction="http://tempuri.org/ICreditTransferService/TransferCreditResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="statusCode")]
        int TransferCredit(out string statusMessage, string sourceMsisdn, string destinationMsisdn, int amountRiyal, int amountBaisa, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditTransferService/TransferCreditWithAdjustmentReason", ReplyAction="http://tempuri.org/ICreditTransferService/TransferCreditWithAdjustmentReasonRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="statusCode")]
        int TransferCreditWithAdjustmentReason(out string statusMessage, string sourceMsisdn, string destinationMsisdn, int amountRiyal, int amountBaisa, string pin, string adjustmentReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditTransferService/GetDenomination", ReplyAction="http://tempuri.org/ICreditTransferService/GetDenominationResponse")]
        System.Collections.Generic.List<decimal> GetDenomination();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditTransferService/TransferCreditWithoutPinforSC", ReplyAction="http://tempuri.org/ICreditTransferService/TransferCreditWithoutPinforSCResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="statusCode")]
        int TransferCreditWithoutPinforSC(out string statusMessage, string sourceMsisdn, string destinationMsisdn, decimal amountRiyal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditTransferService/ValidateTransferInputs", ReplyAction="http://tempuri.org/ICreditTransferService/ValidateTransferInputsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="statusCode")]
        int ValidateTransferInputs(out string statusMessage, string sourceMsisdn, string destinationMsisdn, decimal amountRiyal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditTransferServiceChannel : CreditTransferTestClient.CreditTransfer.ICreditTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditTransferServiceClient : System.ServiceModel.ClientBase<CreditTransferTestClient.CreditTransfer.ICreditTransferService>, CreditTransferTestClient.CreditTransfer.ICreditTransferService {
        
        public CreditTransferServiceClient() {
        }
        
        public CreditTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TransferCredit(out string statusMessage, string sourceMsisdn, string destinationMsisdn, int amountRiyal, int amountBaisa, string pin) {
            return base.Channel.TransferCredit(out statusMessage, sourceMsisdn, destinationMsisdn, amountRiyal, amountBaisa, pin);
        }
        
        public int TransferCreditWithAdjustmentReason(out string statusMessage, string sourceMsisdn, string destinationMsisdn, int amountRiyal, int amountBaisa, string pin, string adjustmentReason) {
            return base.Channel.TransferCreditWithAdjustmentReason(out statusMessage, sourceMsisdn, destinationMsisdn, amountRiyal, amountBaisa, pin, adjustmentReason);
        }
        
        public System.Collections.Generic.List<decimal> GetDenomination() {
            return base.Channel.GetDenomination();
        }
        
        public int TransferCreditWithoutPinforSC(out string statusMessage, string sourceMsisdn, string destinationMsisdn, decimal amountRiyal) {
            return base.Channel.TransferCreditWithoutPinforSC(out statusMessage, sourceMsisdn, destinationMsisdn, amountRiyal);
        }
        
        public int ValidateTransferInputs(out string statusMessage, string sourceMsisdn, string destinationMsisdn, decimal amountRiyal) {
            return base.Channel.ValidateTransferInputs(out statusMessage, sourceMsisdn, destinationMsisdn, amountRiyal);
        }
    }
}
