#!/bin/bash
# Code generated by Cursor
# Simple script to test coverage generation locally

echo "🧪 Testing Coverage Generation"
echo "=============================="

# Change to the correct directory
cd "$(dirname "$0")"
echo "Working directory: $(pwd)"

# Clean up any previous test results
echo "🧹 Cleaning up previous test results..."
rm -rf test-results coverage TestResults

# Create directories
echo "📁 Creating test directories..."
mkdir -p test-results coverage

# Run a simple test to see what gets generated
echo "🧪 Running tests with coverage collection..."
echo "Command: dotnet test CreditTransfer.Modern.sln --collect:\"XPlat Code Coverage\" --results-directory ./test-results --verbosity detailed"
echo ""

dotnet test CreditTransfer.Modern.sln \
  --collect:"XPlat Code Coverage" \
  --results-directory ./test-results \
  --verbosity detailed \
  --configuration Release \
  --no-build \
  --logger "console;verbosity=detailed" 2>&1 | tee test-output.log

echo ""
echo "📊 Test execution completed. Analyzing results..."
echo ""

# Show the directory structure
echo "🔍 Test results directory structure:"
find test-results -type f 2>/dev/null | head -20 || echo "No files found in test-results"
echo ""

# Look for any coverage files anywhere
echo "🔍 Searching for coverage files everywhere:"
find . -name "*coverage*" -type f 2>/dev/null | head -10 || echo "No coverage files found anywhere"
echo ""

# Look for cobertura files specifically
echo "🔍 Searching for cobertura files:"
find . -name "*.cobertura.xml" -type f 2>/dev/null || echo "No cobertura files found"
echo ""

# Look for any XML files that might be coverage related
echo "🔍 Searching for all XML files in test results:"
find test-results -name "*.xml" -type f 2>/dev/null || echo "No XML files found in test-results"
echo ""

# Check for TestResults directories (sometimes created by VSTest)
echo "🔍 Checking for TestResults directories:"
find . -name "TestResults" -type d 2>/dev/null | head -5 || echo "No TestResults directories found"
if [ -d "TestResults" ]; then
  echo "Contents of TestResults directory:"
  find TestResults -type f 2>/dev/null | head -10
fi
echo ""

# Show any .trx files
echo "🔍 Searching for TRX files:"
find . -name "*.trx" -type f 2>/dev/null || echo "No TRX files found"
echo ""

# Check what test projects exist and their configuration
echo "🔍 Checking test projects:"
find . -name "*.Tests.csproj" -type f 2>/dev/null || echo "No .Tests.csproj files found"
echo ""

# Show the test output summary
echo "📋 Test execution summary:"
echo "================================"
tail -20 test-output.log 2>/dev/null || echo "No test output available"
echo ""

echo "🎯 Coverage Generation Test Complete"
echo "=================================="
echo "If no coverage files were found, this indicates:"
echo "1. Tests may not be executing successfully"
echo "2. Test projects may not have coverlet.collector package"
echo "3. Coverage collection may not be properly configured"
echo "4. There may be no actual test methods to execute"
echo ""
echo "Check test-output.log for detailed test execution information."