//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTransferTestClient.ProductSelling {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSellingRequest", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class ProductSellingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnActivationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SubscribeOnceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerCode {
            get {
                return this.DealerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerCodeField, value) != true)) {
                    this.DealerCodeField = value;
                    this.RaisePropertyChanged("DealerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNumberField, value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnActivation {
            get {
                return this.IsOnActivationField;
            }
            set {
                if ((this.IsOnActivationField.Equals(value) != true)) {
                    this.IsOnActivationField = value;
                    this.RaisePropertyChanged("IsOnActivation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SubscribeOnce {
            get {
                return this.SubscribeOnceField;
            }
            set {
                if ((this.SubscribeOnceField.Equals(value) != true)) {
                    this.SubscribeOnceField = value;
                    this.RaisePropertyChanged("SubscribeOnce");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResponse", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditTransferTestClient.ProductSelling.booleanResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditTransferTestClient.ProductSelling.lstStringResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreditTransferTestClient.ProductSelling.ProductResponse))]
    public partial class ReturnResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditTransferTestClient.ProductSelling.ResponseResult responseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditTransferTestClient.ProductSelling.ResponseResult response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResult", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class ResponseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage {
            get {
                return this.SuccessMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessageField, value) != true)) {
                    this.SuccessMessageField = value;
                    this.RaisePropertyChanged("SuccessMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="booleanResult", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class booleanResult : CreditTransferTestClient.ProductSelling.ReturnResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool resultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="lstStringResult", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class lstStringResult : CreditTransferTestClient.ProductSelling.ReturnResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] resultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResponse", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class ProductResponse : CreditTransferTestClient.ProductSelling.ReturnResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditTransferTestClient.ProductSelling.ProductCategoryView[] resultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditTransferTestClient.ProductSelling.ProductCategoryView[] result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategoryView", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class ProductCategoryView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditTransferTestClient.ProductSelling.ProductSubCategoryView[] ProductSubCategoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordinal {
            get {
                return this.OrdinalField;
            }
            set {
                if ((this.OrdinalField.Equals(value) != true)) {
                    this.OrdinalField = value;
                    this.RaisePropertyChanged("Ordinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditTransferTestClient.ProductSelling.ProductSubCategoryView[] ProductSubCategories {
            get {
                return this.ProductSubCategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubCategoriesField, value) != true)) {
                    this.ProductSubCategoriesField = value;
                    this.RaisePropertyChanged("ProductSubCategories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSubCategoryView", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class ProductSubCategoryView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditTransferTestClient.ProductSelling.ProductView[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordinal {
            get {
                return this.OrdinalField;
            }
            set {
                if ((this.OrdinalField.Equals(value) != true)) {
                    this.OrdinalField = value;
                    this.RaisePropertyChanged("Ordinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditTransferTestClient.ProductSelling.ProductView[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductView", Namespace="http://schemas.datacontract.org/2004/07/Virgin.Activation.DataContract.OM")]
    [System.SerializableAttribute()]
    public partial class ProductView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DealerCommissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRenewableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubscriptionManagementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DealerCommission {
            get {
                return this.DealerCommissionField;
            }
            set {
                if ((this.DealerCommissionField.Equals(value) != true)) {
                    this.DealerCommissionField = value;
                    this.RaisePropertyChanged("DealerCommission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRenewable {
            get {
                return this.IsRenewableField;
            }
            set {
                if ((this.IsRenewableField.Equals(value) != true)) {
                    this.IsRenewableField = value;
                    this.RaisePropertyChanged("IsRenewable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ordinal {
            get {
                return this.OrdinalField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdinalField, value) != true)) {
                    this.OrdinalField = value;
                    this.RaisePropertyChanged("Ordinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubscriptionManagementID {
            get {
                return this.SubscriptionManagementIDField;
            }
            set {
                if ((this.SubscriptionManagementIDField.Equals(value) != true)) {
                    this.SubscriptionManagementIDField = value;
                    this.RaisePropertyChanged("SubscriptionManagementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Validity {
            get {
                return this.ValidityField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidityField, value) != true)) {
                    this.ValidityField = value;
                    this.RaisePropertyChanged("Validity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductSelling.IProductSellingService")]
    public interface IProductSellingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductSellingService/GetAvailableProducts", ReplyAction="http://tempuri.org/IProductSellingService/GetAvailableProductsResponse")]
        CreditTransferTestClient.ProductSelling.ProductResponse GetAvailableProducts(CreditTransferTestClient.ProductSelling.ProductSellingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductSellingService/SubmitProductSelling", ReplyAction="http://tempuri.org/IProductSellingService/SubmitProductSellingResponse")]
        CreditTransferTestClient.ProductSelling.booleanResult SubmitProductSelling(CreditTransferTestClient.ProductSelling.ProductSellingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductSellingService/GetUsedAdjustmentReasons", ReplyAction="http://tempuri.org/IProductSellingService/GetUsedAdjustmentReasonsResponse")]
        CreditTransferTestClient.ProductSelling.lstStringResult GetUsedAdjustmentReasons();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductSellingServiceChannel : CreditTransferTestClient.ProductSelling.IProductSellingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductSellingServiceClient : System.ServiceModel.ClientBase<CreditTransferTestClient.ProductSelling.IProductSellingService>, CreditTransferTestClient.ProductSelling.IProductSellingService {
        
        public ProductSellingServiceClient() {
        }
        
        public ProductSellingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductSellingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductSellingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductSellingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CreditTransferTestClient.ProductSelling.ProductResponse GetAvailableProducts(CreditTransferTestClient.ProductSelling.ProductSellingRequest request) {
            return base.Channel.GetAvailableProducts(request);
        }
        
        public CreditTransferTestClient.ProductSelling.booleanResult SubmitProductSelling(CreditTransferTestClient.ProductSelling.ProductSellingRequest request) {
            return base.Channel.SubmitProductSelling(request);
        }
        
        public CreditTransferTestClient.ProductSelling.lstStringResult GetUsedAdjustmentReasons() {
            return base.Channel.GetUsedAdjustmentReasons();
        }
    }
}
