apiVersion: v1
kind: Service
metadata:
  name: nobill-external
  namespace: credittransfer
spec:
  type: ExternalName
  externalName: 10.1.132.98
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nobill-external-endpoints
  namespace: credittransfer
subsets:
- addresses:
  - ip: 10.1.132.98
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nobill-external-endpoints
  namespace: credittransfer
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 