// This code was generated by Cursor
using CreditTransfer.Services.WebHandler.Models;

namespace CreditTransfer.Services.WebHandler.Services
{
    /// <summary>
    /// Interface for calling the Credit Transfer REST API
    /// </summary>
    public interface ICreditTransferApiClient
    {
        /// <summary>
        /// Transfers credit using the REST API
        /// </summary>
        /// <param name="request">Credit transfer request</param>
        /// <returns>Credit transfer response</returns>
        Task<CreditTransferApiResponse> TransferCreditAsync(CreditTransferRequest request);
    }
} 