// This code was generated by Cursor
namespace CreditTransfer.Services.WebHandler.Services
{
    /// <summary>
    /// Interface for Keycloak JWT authentication
    /// </summary>
    public interface IKeycloakAuthenticationService
    {
        /// <summary>
        /// Acquires JWT token from Keycloak
        /// </summary>
        /// <returns>JWT access token</returns>
        Task<string> GetAccessTokenAsync();

        /// <summary>
        /// Validates if current cached token is valid
        /// </summary>
        /// <returns>True if token is valid and not expired</returns>
        bool IsTokenValid();

        /// <summary>
        /// Forces token refresh
        /// </summary>
        /// <returns>New JWT access token</returns>
        Task<string> RefreshTokenAsync();

        /// <summary>
        /// Clears the cached token (useful for error recovery)
        /// </summary>
        void ClearCachedToken();

        /// <summary>
        /// Gets token expiry information (for monitoring)
        /// </summary>
        /// <returns>Token expiry time or null if no token cached</returns>
        DateTime? GetTokenExpiry();
    }
} 