// This code was generated by Cursor
using CreditTransfer.Services.WebHandler.Models;

namespace CreditTransfer.Services.WebHandler.Services
{
    /// <summary>
    /// Interface for XML request/response processing
    /// </summary>
    public interface IXmlProcessingService
    {
        /// <summary>
        /// Parses incoming XML umsprot request
        /// </summary>
        /// <param name="xmlContent">Raw XML content</param>
        /// <returns>Parsed transfer request</returns>
        CreditTransferRequest ParseXmlRequest(string xmlContent);

        /// <summary>
        /// Generates XML response from API response
        /// </summary>
        /// <param name="apiResponse">API response</param>
        /// <returns>XML response string</returns>
        string GenerateXmlResponse(CreditTransferApiResponse apiResponse);

        /// <summary>
        /// Generates XML error response
        /// </summary>
        /// <param name="errorCode">Error code</param>
        /// <param name="errorMessage">Error message</param>
        /// <returns>XML error response string</returns>
        string GenerateXmlErrorResponse(int errorCode, string errorMessage);
    }
} 