//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTransferEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreditTransferMessages_Ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreditTransferMessages_Ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreditTransferEngine.Resources.CreditTransferMessages-Ar", typeof(CreditTransferMessages_Ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. SAR {0} has been successfully transferred to {1}. Your new balance is SAR {2}..
        /// </summary>
        internal static string CreditTransferSuccessMsgA {
            get {
                return ResourceManager.GetString("CreditTransferSuccessMsgA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR {0} has been successfully received from {2}. Your new balance is  SAR {3}..
        /// </summary>
        internal static string CreditTransferSuccessMsgB {
            get {
                return ResourceManager.GetString("CreditTransferSuccessMsgB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transaction has been expired..
        /// </summary>
        internal static string TransactionExpired {
            get {
                return ResourceManager.GetString("TransactionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found..
        /// </summary>
        internal static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your ID / Iqama number, {0} wants to transfer the amount SAR {1}..
        /// </summary>
        internal static string VirginCreditTransferSMS {
            get {
                return ResourceManager.GetString("VirginCreditTransferSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID number you entered is incorrect. Please re-enter the correct ID number..
        /// </summary>
        internal static string WrongIdNumber {
            get {
                return ResourceManager.GetString("WrongIdNumber", resourceCulture);
            }
        }
    }
}
