// This code was generated by Cursor
namespace CreditTransfer.Services.WebHandler.Models
{
    /// <summary>
    /// Credit transfer request model
    /// </summary>
    public class CreditTransferRequest
    {
        public string SourceMsisdn { get; set; } = string.Empty;
        public string DestinationMsisdn { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public decimal AmountRiyal { get; set; }
        public decimal AmountBaisa { get; set; }
        public string Pin { get; set; } = string.Empty;
    }

    /// <summary>
    /// Credit transfer API response model
    /// </summary>
    public class CreditTransferApiResponse
    {
        public bool Success { get; set; }
        public int StatusCode { get; set; }
        public string StatusMessage { get; set; } = string.Empty;
        public string? TransactionId { get; set; }
        public DateTime Timestamp { get; set; }
    }

    /// <summary>
    /// XML request parameters extracted from umsprot structure
    /// </summary>
    public class XmlRequestParameters
    {
        public string SourceMsisdn { get; set; } = string.Empty;
        public string DestinationMsisdn { get; set; } = string.Empty;
        public int AmountRiyal { get; set; }
        public int AmountHalala { get; set; }
        public string Pin { get; set; } = string.Empty;
    }

    /// <summary>
    /// Response constants matching original system
    /// </summary>
    public static class ServiceHttpResponse
    {
        public const string USSDPositive = "OK";
        public const string USSDNegative = "NOK";
        public const int USSDGenericErrorCode = -1;
    }

    /// <summary>
    /// Handler response constants
    /// </summary>
    public static class HandlerResponse
    {
        public const int BadRequestCode = 32;
        public const string BadRequestMessage = "Bad Request";
        public const int ServiceUnavailableCode = -1;
        public const string ServiceUnavailableMessage = "NOK";
    }

    /// <summary>
    /// XML parameter names from original system
    /// </summary>
    public static class XmlUSSDParams
    {
        public const string SourceMsisdn = "SourceMsisdn";
        public const string DestinationMsisdn = "DestinationMsisdn";
        public const string AmountRiyal = "AmountRiyal";
        public const string AmountHalala = "AmountHalala";
        public const string PIN = "PIN";
    }

    /// <summary>
    /// HTTP response templates matching original system
    /// </summary>
    public static class HttpResponseTemplates
    {
        public const string USSD = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><umsprot version=\"1\"><exec_rsp result=\"{0}\" diagnostic=\"\"><data name=\"failreason\">{1}</data></exec_rsp></umsprot>";
    }
} 